# Generated by Django 5.0.1 on 2024-01-26 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0002_alter_message_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thread",
            old_name="user",
            new_name="users",
        ),
    ]
