# Generated by Django 5.0.1 on 2024-01-27 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0003_rename_user_thread_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="thread",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
